// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NoraPA.API;

#nullable disable

namespace NoraPA.API.Migrations
{
    [DbContext(typeof(NoraDbContext))]
    [Migration("20260113011415_SmartRoutingUpdates")]
    partial class SmartRoutingUpdates
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("NoraPA.Core.AiAnalysis", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("AnalyzedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("analyzed_at");

                    b.Property<int>("Complexity")
                        .HasColumnType("INTEGER")
                        .HasColumnName("task_complexity");

                    b.Property<decimal>("CostUsd")
                        .HasColumnType("TEXT")
                        .HasColumnName("cost_usd");

                    b.Property<string>("DeadlinesAnalysis")
                        .HasColumnType("TEXT")
                        .HasColumnName("deadlines_analysis");

                    b.Property<string>("DocumentsAnalysis")
                        .HasColumnType("TEXT")
                        .HasColumnName("documents_analysis");

                    b.Property<string>("FinancialRecordsAnalysis")
                        .HasColumnType("TEXT")
                        .HasColumnName("financial_records_analysis");

                    b.Property<string>("GeneralAnalysis")
                        .HasColumnType("TEXT")
                        .HasColumnName("general_analysis");

                    b.Property<string>("ImportanceAnalysis")
                        .HasColumnType("TEXT")
                        .HasColumnName("importance_analysis");

                    b.Property<string>("LifeDomainAnalysis")
                        .HasColumnType("TEXT")
                        .HasColumnName("life_domain_analysis");

                    b.Property<long>("MessageId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("message_id");

                    b.Property<string>("ModelUsed")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("model_used");

                    b.Property<string>("ObligationsAnalysis")
                        .HasColumnType("TEXT")
                        .HasColumnName("obligations_analysis");

                    b.Property<int>("ProcessingTimeMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("processing_time_ms");

                    b.Property<string>("RawResponse")
                        .HasColumnType("TEXT")
                        .HasColumnName("raw_response");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("pending")
                        .HasColumnName("status");

                    b.Property<string>("Summary")
                        .HasColumnType("TEXT")
                        .HasColumnName("summary");

                    b.HasKey("Id");

                    b.HasIndex("MessageId");

                    b.ToTable("ai_analyses");
                });

            modelBuilder.Entity("NoraPA.Core.AiSettings", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("ApiEndpoint")
                        .HasColumnType("TEXT")
                        .HasColumnName("api_endpoint");

                    b.Property<string>("ApiKey")
                        .HasColumnType("TEXT")
                        .HasColumnName("api_key");

                    b.Property<int>("BudgetMode")
                        .HasColumnType("INTEGER")
                        .HasColumnName("budget_mode");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<bool>("CrossProviderEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("cross_provider_enabled");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<int>("MaxTokens")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(4096)
                        .HasColumnName("max_tokens");

                    b.Property<string>("Model")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("model");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("provider");

                    b.Property<decimal>("Temperature")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue(0.7m)
                        .HasColumnName("temperature");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("ai_settings");
                });

            modelBuilder.Entity("NoraPA.Core.AiUsageLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<long?>("AnalysisId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("analysis_id");

                    b.Property<int>("Complexity")
                        .HasColumnType("INTEGER")
                        .HasColumnName("complexity");

                    b.Property<decimal>("CostUsd")
                        .HasColumnType("TEXT")
                        .HasColumnName("cost_usd");

                    b.Property<int>("InputTokens")
                        .HasColumnType("INTEGER")
                        .HasColumnName("input_tokens");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("model_name");

                    b.Property<int>("OutputTokens")
                        .HasColumnType("INTEGER")
                        .HasColumnName("output_tokens");

                    b.Property<int?>("QualityRating")
                        .HasColumnType("INTEGER")
                        .HasColumnName("quality_rating");

                    b.Property<int>("ResponseTimeMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("response_time_ms");

                    b.Property<int>("TaskType")
                        .HasColumnType("INTEGER")
                        .HasColumnName("task_type");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT")
                        .HasColumnName("timestamp");

                    b.HasKey("Id");

                    b.ToTable("ai_usage_logs");
                });

            modelBuilder.Entity("NoraPA.Core.AppSettings", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("key");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT")
                        .HasColumnName("value");

                    b.HasKey("Key");

                    b.ToTable("app_settings");
                });

            modelBuilder.Entity("NoraPA.Core.Deadline", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<bool>("Critical")
                        .HasColumnType("INTEGER")
                        .HasColumnName("critical");

                    b.Property<DateTime?>("DeadlineDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("deadline_date");

                    b.Property<string>("DeadlineType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("absolute")
                        .HasColumnName("deadline_type");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<long>("MessageId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("message_id");

                    b.Property<long?>("ObligationId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("obligation_id");

                    b.Property<TimeSpan?>("RelativeDuration")
                        .HasColumnType("TEXT")
                        .HasColumnName("relative_duration");

                    b.Property<string>("RelativeTrigger")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("relative_trigger");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("active")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("MessageId");

                    b.HasIndex("ObligationId");

                    b.ToTable("deadlines");
                });

            modelBuilder.Entity("NoraPA.Core.Message", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("BodyHtml")
                        .HasColumnType("TEXT")
                        .HasColumnName("body_html");

                    b.Property<string>("BodyPlain")
                        .HasColumnType("TEXT")
                        .HasColumnName("body_plain");

                    b.Property<string>("FromAddress")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("from_address");

                    b.Property<string>("FromName")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("from_name");

                    b.Property<string>("Importance")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("importance");

                    b.Property<string>("LifeDomain")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("life_domain");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("processed_at");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("received_at");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("source");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("source_id");

                    b.Property<string>("Subject")
                        .HasColumnType("TEXT")
                        .HasColumnName("subject");

                    b.PrimitiveCollection<string>("ToAddresses")
                        .HasColumnType("TEXT")
                        .HasColumnName("to_addresses");

                    b.HasKey("Id");

                    b.HasIndex("Source", "SourceId")
                        .IsUnique();

                    b.ToTable("messages");
                });

            modelBuilder.Entity("NoraPA.Core.Obligation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("action");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("completed_at");

                    b.Property<decimal?>("ConfidenceScore")
                        .HasColumnType("TEXT")
                        .HasColumnName("confidence_score");

                    b.Property<string>("Consequence")
                        .HasColumnType("TEXT")
                        .HasColumnName("consequence");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<TimeSpan?>("EstimatedTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("estimated_time");

                    b.Property<bool>("Mandatory")
                        .HasColumnType("INTEGER")
                        .HasColumnName("mandatory");

                    b.Property<long>("MessageId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("message_id");

                    b.Property<int?>("Priority")
                        .HasColumnType("INTEGER")
                        .HasColumnName("priority");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("pending")
                        .HasColumnName("status");

                    b.Property<string>("TriggerType")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("trigger_type");

                    b.Property<string>("TriggerValue")
                        .HasColumnType("TEXT")
                        .HasColumnName("trigger_value");

                    b.HasKey("Id");

                    b.HasIndex("MessageId");

                    b.ToTable("obligations");
                });

            modelBuilder.Entity("NoraPA.Core.Task", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("completed_at");

                    b.Property<string>("ContextLink")
                        .HasColumnType("TEXT")
                        .HasColumnName("context_link");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("due_date");

                    b.Property<long?>("ObligationId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("obligation_id");

                    b.Property<int?>("Priority")
                        .HasColumnType("INTEGER")
                        .HasColumnName("priority");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("pending")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("ObligationId")
                        .IsUnique();

                    b.ToTable("tasks");
                });

            modelBuilder.Entity("NoraPA.Core.AiAnalysis", b =>
                {
                    b.HasOne("NoraPA.Core.Message", "Message")
                        .WithMany("AiAnalyses")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Message");
                });

            modelBuilder.Entity("NoraPA.Core.Deadline", b =>
                {
                    b.HasOne("NoraPA.Core.Message", "Message")
                        .WithMany("Deadlines")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NoraPA.Core.Obligation", "Obligation")
                        .WithMany("Deadlines")
                        .HasForeignKey("ObligationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Message");

                    b.Navigation("Obligation");
                });

            modelBuilder.Entity("NoraPA.Core.Obligation", b =>
                {
                    b.HasOne("NoraPA.Core.Message", "Message")
                        .WithMany("Obligations")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Message");
                });

            modelBuilder.Entity("NoraPA.Core.Task", b =>
                {
                    b.HasOne("NoraPA.Core.Obligation", "Obligation")
                        .WithOne("Task")
                        .HasForeignKey("NoraPA.Core.Task", "ObligationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Obligation");
                });

            modelBuilder.Entity("NoraPA.Core.Message", b =>
                {
                    b.Navigation("AiAnalyses");

                    b.Navigation("Deadlines");

                    b.Navigation("Obligations");
                });

            modelBuilder.Entity("NoraPA.Core.Obligation", b =>
                {
                    b.Navigation("Deadlines");

                    b.Navigation("Task");
                });
#pragma warning restore 612, 618
        }
    }
}
